apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-sre-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pumpcard/agent-sre
    targetRevision: main
    path: charts
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-sre-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
