image:
  repository: 258131496527.dkr.ecr.us-west-2.amazonaws.com/agent-sre

namespace: agent-sre-dev

replicaCount: 1

ingress:
  enabled: true
  host: api-dev.pump.co
  path: /agent-sre

env:
  DEPLOYMENT_ENV: development
  DD_ENV: dev

secretsManagerPath: agent-sre-dev
